### ISSUE TITLE
This method could be named: "public void loginWithValidCredentials" .

### ISSUE THREAD

**Issue by holaszmoni** [stefana24/SerenityTask#1]
https://github.com/stefana24/SerenityTask/blob/2e11a3ef750a8aa90183ef5aaca6bc81739f7e62/src/test/java/com/evozon/steps/serenity/LogInStep.java#L34

**Comment by AndreeaMahulet** [comment]
38a4c05e983e92d70e0a26712eb6fc55833258ea
