### ISSUE TITLE
This method could be named: "public void verifyMessageWhenProductWasAdded" .

### ISSUE THREAD

**Issue by holaszmoni** [stefana24/SerenityTask#9]
https://github.com/stefana24/SerenityTask/blob/2e11a3ef750a8aa90183ef5aaca6bc81739f7e62/src/test/java/com/evozon/steps/serenity/ShoppingSteps.java#L12

**Comment by AndreeaMahulet** [comment]
acc9be2b91c38140b355d1cd50a436aae33ecc90
